### ISSUE TITLE
rollbar-android deprecated

### ISSUE THREAD

**Issue by devitito** [rollbar/rollbar-cordova#4]
rollbar-android is deprecated. They recommend the use of rollbar-java.

From what I can see i plugin.xml, rollbar-cordova still use rollbar-android. And I get this error at runtime :
` java.lang.NoClassDefFoundError: Failed resolution of: Lorg/jacoco/agent/rt/internal_8ff85ea/Offline;
        at com.rollbar.android.Rollbar.$jacocoInit(Unknown Source:13)
        at com.rollbar.android.Rollbar.init(Unknown Source:0)
        at com.rollbar.cordova.RollbarCordova.initialize(RollbarCordova.java:25)
        at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:57)
        at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
        at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:97)
        at org.apache.cordova.PluginManager.init(PluginManager.java:86)
        at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:117)
        at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:149)
        at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:224)
        at com.inoviateam.traqfood.MainActivity.onCreate(MainActivity.java:39)
        at android.app.Activity.performCreate(Activity.java:7930)
    	at android.app.Activity.`

**Comment by waltjones** [comment]
@devitito This is the android build target of rollbar-java, and is the correct/current rollbar-android.

The error you hit was a build issue in v1.7.0. It is fixed now in v1.7.1. https://github.com/rollbar/rollbar-java/releases

**Comment by devitito** [comment]
Thanks!

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Walt Jones <notifications@github.com>
Envoyé : Monday, April 27, 2020 5:37:25 PM
À : rollbar/rollbar-cordova <rollbar-cordova@noreply.github.com>
Cc : devitito <the.devitito@gmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [rollbar/rollbar-cordova] rollbar-android deprecated (#4)


@devitito<https://github.com/devitito> This is the android build target of rollbar-java, and is the correct/current rollbar-android.

The error you hit was a build issue in v1.7.0. It is fixed now in v1.7.1. https://github.com/rollbar/rollbar-java/releases
